services:
  - type: web
    name: TransomSahab
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm install --production
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
